[module]

version = "0.1.0"

[[areas.frontend.routing]]
path = "#*"
target = 'Buckyball\FrontendUI\Frontend\Controller\Status'

[[areas.frontend.routing]]
path = "/"
target = 'Buckyball\FrontendUI\Frontend\Controller\Home'
type = "action"

[[areas.frontend.routing]]
path = "/user/.action/?:id"
target = 'Buckyball\User\Frontend\Controller\Users'
type = "controller"

[[areas.frontend.routing]]
path = "/pub"
target = "@Buckyball/FrontendUI/pub"
type = "pub"

[[areas.frontend.routing]]
path = "/*page"
target = "@Buckyball/FrontendUI/views/static"
type = "proxy"