[module]

version = "0.1.0"

[[areas.frontend.routing]]
route = "/"
class = 'Buckyball\FrontendUI\Frontend\Controller\Home'

[[areas.frontend.routing]]
route = "/user/.action/?:id"
class = 'Buckyball\User\Frontend\Controller\Users'

[[areas.frontend.routing]]
#route = "^/pub/js/(.*)\.js$"
route = "^/pub/(js|css|img)/(.*)\.(js|css|png|gif|jpg)$"
class = "Buckyball\Core\Controller\Pub"
root = "@Buckyball/FrontendUI/pub"

[[areas.frontend.routing]]
route = "/*page"
target = "Buckyball\Core\Controller\Pub"
root = "@Buckyball/FrontendUI/views/static"
